# Generated by Django 4.2.13 on 2024-09-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_response_announcement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
